[package]
name = "control_law"
version = "0.1.0"
edition = "2021"

[dependencies]
pid = "4.0.0"
micromath = "2.1.0"
adskalman = { version = "0.15.1", default-features = false }

[features]
std = []
telemetry = []
